/**
 * Media Proxy Service (Cloudflare Worker)
 * 
 * This worker acts as a secure streaming proxy between the Next.js application
 * and Google Drive. It enforces authorization using a short-lived Signed JWT 
 * generated by the application.
 * 
 * Expected Environment Variables:
 * - MEDIA_SECRET_KEY: Same secret used in Next.js to verify JWTs
 * - GOOGLE_DRIVE_CLIENT_EMAIL: Service Account Email
 * - GOOGLE_DRIVE_PRIVATE_KEY: Service Account Private Key
 * 
 * Flow:
 * 1. Client requests `/?token=<jwt>` (with Range headers for video)
 * 2. Worker verifies JWT signature and expiration.
 * 3. Worker extracts `drive_file_id` from JWT payload.
 * 4. Worker authenticates with Google (using JWT-based OAuth for Service Accounts).
 * 5. Worker streams from `https://www.googleapis.com/drive/v3/files/<id>?alt=media`.
 * 6. Worker returns the stream and correct status codes (206/200) to client.
 */

import { jwtVerify } from 'jose';

// Helper to generate Google Service Account OAuth token
async function getGoogleToken(env: any) {
  const iat = Math.floor(Date.now() / 1000);
  const exp = iat + 3600;
  const payload = {
    iss: env.GOOGLE_DRIVE_CLIENT_EMAIL,
    scope: 'https://www.googleapis.com/auth/drive.file',
    aud: 'https://oauth2.googleapis.com/token',
    exp,
    iat
  };

  const header = { alg: 'RS256', typ: 'JWT' };
  
  // Create and sign JWT for Google OAuth (Using Web Crypto API available in Workers)
  // To avoid bringing a heavy library, typically one uses something like `jose` or raw Web Crypto.
  // For the sake of this architectural implementation, we assume `jose` is bundled or available.
  const privateKeyStr = env.GOOGLE_DRIVE_PRIVATE_KEY.replace(/\\n/g, '\n');
  const privateKey = await importPKCS8(privateKeyStr, 'RS256');
  
  const assertion = await new SignJWT(payload)
    .setProtectedHeader(header)
    .sign(privateKey);

  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
      assertion
    })
  });

  const data = await response.json();
  return data.access_token;
}

// NOTE: importPKCS8 and SignJWT are from 'jose'. You can bundle this worker with webpack/esbuild.
import { importPKCS8, SignJWT } from 'jose';

export default {
  async fetch(request: Request, env: any, ctx: any): Promise<Response> {
    const url = new URL(request.url);
    const token = url.searchParams.get('token');

    // CORS handling
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': env.ALLOWED_ORIGIN || '*',
          'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS',
          'Access-Control-Allow-Headers': 'Range, Authorization',
        }
      });
    }

    if (!token) {
      return new Response('Missing token', { status: 400 });
    }

    try {
      // 1. Verify Application JWT
      const secret = new TextEncoder().encode(env.MEDIA_SECRET_KEY);
      const { payload } = await jwtVerify(token, secret);
      const driveFileId = payload.drive_file_id as string;

      if (!driveFileId) {
        return new Response('Invalid token payload', { status: 400 });
      }

      // 2. Get Google Drive Access Token
      // In a real production worker, you should cache this access token until it expires
      const driveToken = await getGoogleToken(env);

      // 3. Forward request to Google Drive
      const driveUrl = `https://www.googleapis.com/drive/v3/files/${driveFileId}?alt=media`;
      
      const headers = new Headers();
      headers.set('Authorization', `Bearer ${driveToken}`);
      
      // Forward Range header if present
      const range = request.headers.get('Range');
      if (range) {
        headers.set('Range', range);
      }

      const driveResponse = await fetch(driveUrl, { headers });

      // 4. Stream response back to client
      const responseHeaders = new Headers(driveResponse.headers);
      responseHeaders.set('Access-Control-Allow-Origin', env.ALLOWED_ORIGIN || '*');

      return new Response(driveResponse.body, {
        status: driveResponse.status,
        statusText: driveResponse.statusText,
        headers: responseHeaders
      });

    } catch (err) {
      console.error(err);
      return new Response('Unauthorized or Invalid Token', { status: 403 });
    }
  }
};
